@startuml 


left to right direction


actor Bruger

rectangle OptiMind{
  Bruger --> (Log humør)
  Bruger --> (Skriv kommentar)
  Bruger --> (humøroversigt)
  Bruger --> (Log aktivitet)
  Bruger --> (Tilføj aktivitet)

  

}
@enduml
